import Form from '@/components/Form';
import React from 'react';
import { Metadata } from 'next';

export const metadata: Metadata = {
    title: 'Login',
    description: 'Generated by create next app',
};

function LoginPage(): React.ReactNode {
    return (
        <div>
            <Form type="login" />
        </div>
    );
}

export default LoginPage;
