import { Metadata } from 'next';

export const metadata: Metadata = {
    title: 'Menu',
    description: 'Generated by create next app',
};

function MenuPage() {
    return <div>Product</div>;
}

export default MenuPage;
