import Header from '@/components/Header';
import { Metadata } from 'next';

export const metadata: Metadata = {
    title: 'Checkout',
    description: 'Generated by create next app',
};

function WaiterCheckout() {
    return (
        <div>
            <Header />
            Checkout
        </div>
    );
}

export default WaiterCheckout;
