import { Metadata } from 'next';
import Table from '@/components/Table';

export const metadata: Metadata = {
    title: 'Menu',
    description: 'Generated by create next app',
};

function MenuPage() {
    return (
        <div>
            <div className="mt-8">
                <Table></Table>
            </div>
        </div>
    );
}

export default MenuPage;
