import type { Metadata } from 'next';
import '../globals.css';
import Sidebar from '@/components/Sidebar';
import SidebarProvider from '@/provider/SidebarProvider';
import LayoutContainer from '@/components/LayoutContainer';
import DashboardHeader from '@/components/DashboardHeader';

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function Layout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <section>
            <SidebarProvider>
                <Sidebar />
                <LayoutContainer>
                    <DashboardHeader />
                    {children}
                </LayoutContainer>
            </SidebarProvider>
        </section>
    );
}
