import Form from '@/components/Form';
import React from 'react';
import { Metadata } from 'next';

export const metadata: Metadata = {
    title: 'Register',
    description: 'Generated by create next app',
};

function Register(): React.ReactNode {
    return (
        <div>
            <Form type="register" />
        </div>
    );
}

export default Register;
