import React from 'react';
import { Metadata } from 'next';

export const metadata: Metadata = {
    title: 'Login',
    description: 'Generated by create next app',
};

function WaiterHome(): React.ReactNode {
    return <div>Waiter Home</div>;
}

export default WaiterHome;
