import React from 'react';
import { Metadata } from 'next';

export const metadata: Metadata = {
    title: 'Login',
    description: 'Generated by create next app',
};

function ChefHome(): React.ReactNode {
    return <div>Home</div>;
}

export default ChefHome;
