import type { Metadata } from 'next';
import '../globals.css';
import Header from '@/components/Header';

export const metadata: Metadata = {
    title: 'Waiter Home',
    description: 'Generated by create next app',
};

export default function Layout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <section>
            {/* <Header /> */}
            {children}
        </section>
    );
}
