import type { Metadata } from 'next';
import { Roboto } from 'next/font/google';
import '../globals.css';
import Header from '@/components/Header';

const inter = Roboto({ subsets: ['latin'], weight: ['100', '300', '400', '500', '700'] });

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en" suppressHydrationWarning>
            <body className={`${inter.className} min-h-screen bg-secondary-white dark:bg-secondary-dark`}>
                <Header />
                <div className="px-12">{children}</div>
            </body>
        </html>
    );
}
