import React from 'react';
import { Metadata } from 'next';
import Carousel from '@/components/Carousel';

export const metadata: Metadata = {
    title: 'Home',
    description: 'Generated by create next app',
};

function Home() {
    return (
        <div className="">
            <Carousel />
        </div>
    );
}

export default Home;
