import React from 'react';
import { Metadata } from 'next';

export const metadata: Metadata = {
    title: 'Login',
    description: 'Generated by create next app',
};

function ChefOrderLists(): React.ReactNode {
    return <div>Order List</div>;
}

export default ChefOrderLists;
