import { Metadata } from 'next';

export const metadata: Metadata = {
    title: 'Analyst',
    description: 'Generated by create next app',
};

function AnalystPage() {
    return <div>analyst</div>;
}

export default AnalystPage;
