import { Metadata } from 'next';

export const metadata: Metadata = {
    title: 'History',
    description: 'Generated by create next app',
};
function HistoryPage() {
    return <div>history</div>;
}

export default HistoryPage;
