import { Metadata } from 'next';

export const metadata: Metadata = {
    title: 'Reservation',
    description: 'Generated by create next app',
};

function ReservationPage() {
    return (
        <div>
            
        </div>
    );
}

export default ReservationPage;
